---
# tasks file for /etc/ansible/roles/java
- name: Import tasks for CentOS
  import_tasks: yum.yml
  when: ansible_distribution == 'CentOS'
- name: Import tasks for Debian/Ubuntu
  import_tasks: apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
...
